apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: myapp
    env: development
  annotations:
    description: "Pod running in development environment"
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do echo "Pod1: Hello from development"; sleep 5; done']

---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: myapp
    env: staging
  annotations:
    description: "Pod running in staging environment"
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do echo "Pod2: Hello from staging"; sleep 5; done']

---

apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    app: myapp
    env: production
  annotations:
    description: "Pod running in production environment"
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do echo "Pod3: Hello from production"; sleep 5; done']
